workflows:
  ios-simulator-build:
    name: Build iOS Debug for Simulator
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..
      - name: Build iOS for Simulator
        script: |
          flutter build ios --debug --no-codesign --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
