workflows:
  ios-debug:
    name: Build iOS Debug for Simulator
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter & iOS build
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          cd ios
          pod deintegrate
          cd ..
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS debug (simulator)
        script: |
          flutter build ios --debug --no-codesign --simulator
