workflows:
  ios-workflow:
    name: Build iOS
    max_build_duration: 15
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.company.awesomeApp"
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      - name: Clean CocoaPods & reinstall
        script: |
          cd ios
          rm -rf Pods
          rm -rf .symlinks
          rm -rf Flutter/Flutter.framework
          rm -f Podfile.lock
          pod deintegrate || true
          pod install
          cd ..

      - name: Build iOS debug (simulator)
        script: |
          flutter build ios --debug --no-codesign --simulator

    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
