workflows:
  ios-build:
    name: Build iOS Debug
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
