workflows:
  ios-debug:
    name: Build iOS Debug for Simulator
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths: [] # Tắt cache hoàn toàn

    scripts:
      - name: Clean & Remove iOS Build Cache
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Generated.xcconfig
          rm -rf ios/Podfile.lock
          cd ios
          pod deintegrate || true
          cd ..

      - name: Get Dependencies
        script: flutter pub get

      - name: Install Pods (fresh)
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS Debug for Simulator
        script: flutter build ios --debug --no-codesign --simulator
