workflows:
  ios-debug-simulator:
    name: iOS Debug Build (Simulator)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and prepare project
        script: |
          #!/usr/bin/env bash
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Generated.xcconfig
          rm -rf ios/Podfile.lock

          cd ios
          pod deintegrate || true
          pod cache clean --all
          cd ..

          flutter pub get

          cd ios
          pod install --repo-update
          cd ..
      
      - name: Build iOS Debug (Simulator)
        script: |
          #!/usr/bin/env bash
          flutter build ios --debug --no-codesign --simulator

    artifacts:
      - build/ios/**/*.app

    
