workflows:
  ios-workflow:
    name: Build iOS
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter pub get
        script: |
          flutter clean
          flutter pub get

      - name: Clean CocoaPods and reinstall
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework
          pod deintegrate || true
          pod install
          cd ..

      - name: Build iOS for simulator
        script: |
          flutter build ios --debug --no-codesign --simulator

    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
