platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_application_path = File.expand_path('..', __FILE__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(flutter_application_path)
end
